import adm from "@/assets/images/profile/adm.png";

export const rankData = [
  {
    image: adm,
    ranking: 1,
    name: "PLAYER NAME",
    amount: 10,
    streak: 10,
    status: true,
    color: "#FFAF0F",
  },
  {
    image: adm,
    ranking: 2,
    name: "PLAYER NAME",
    amount: 10,
    streak: 10,
    status: true,
    color: "#69FF7D",
  },
  {
    image: adm,
    ranking: 3,
    name: "PLAYER NAME",
    amount: 10,
    streak: 10,
    status: true,
    color: "#A721DA",
  },
  {
    image: adm,
    ranking: 4,
    name: "PLAYER NAME",
    amount: 10,
    streak: 10,
    status: true,
    color: "#BBBBBB",
  },
  {
    image: adm,
    ranking: 5,
    name: "PLAYER NAME",
    amount: 10,
    streak: 10,
    status: true,
    color: "#BBBBBB",
  },
  {
    image: adm,
    ranking: 6,
    name: "PLAYER NAME",
    amount: 10,
    streak: 10,
    status: true,
    color: "#BBBBBB",
  },
  {
    image: adm,
    ranking: 7,
    name: "PLAYER NAME",
    amount: 10,
    streak: 10,
    status: true,
    color: "#BBBBBB",
  },
  {
    image: adm,
    ranking: 8,
    name: "PLAYER NAME",
    amount: 10,
    streak: 10,
    status: true,
    color: "#BBBBBB",
  },
  {
    image: adm,
    ranking: 9,
    name: "PLAYER NAME",
    amount: 10,
    streak: 10,
    status: true,
    color: "#BBBBBB",
  },
  {
    image: adm,
    ranking: 10,
    name: "PLAYER NAME",
    amount: 10,
    streak: 10,
    status: true,
    color: "#BBBBBB",
  },
  {
    image: adm,
    ranking: 11,
    name: "PLAYER NAME",
    amount: 10,
    streak: 10,
    status: true,
    color: "#BBBBBB",
  },
  {
    image: adm,
    ranking: 12,
    name: "PLAYER NAME",
    amount: 10,
    streak: 10,
    status: true,
    color: "#BBBBBB",
  },
];
